export const products = [
    {
        id: "1",
        titulo: "PORTA TABLITA ASADO X1 CALADO RECTANG",
        imagen: "https://www.belloexport.com.ar/wp-content/uploads/2022/04/HZ_7141-1.jpg",
        descripcion: "DETALLES DEL PRODUCTO: Material de alta calidad, muy fácil de limpiar y una excelente terminación. Para 1 persona.",
        materiales: "MATERIALES: Ecocuero tricapa y madera leuka compensada.",
        medidas: "MEDIDAS: Estuche:  33cm. X 23cm. X 12cm. Tabla:  23cm. X 23cm, X 1.5cm. ",
        elementos: "ELEMENTOS (18 PIEZAS):  1 Bolso de ecocuero. 4 Platos de madera cuadrados de madera de Leuka. 4 Cuchillos t/Tramontina con mango de madera. 4 Tenedores t/Tramontina con mango de madera. 4 Vasos de acero. 1 Repasador de algodón.",
        precio: "2500",
        stock: "17",
    },
    {
        id: "2",
        titulo: "SET ASADO SERIE 2 P/4",
        imagen: "https://www.belloexport.com.ar/wp-content/uploads/2018/05/P09201_06-1.jpg",
        descripcion: "DETALLES DEL PRODUCTO: Material de alta calidad, muy fácil de limpiar y unaexcelente terminación. Para 4 personas.",
        precio: "4000",
        stock: "15",
    },
    {
        id: "3",
        titulo:"JUEGO ASADOR 3 PIEZAS C/MENSULA",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2021/11/1022_037.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Hechos de Metal. Mangos madera ergonómicos y sólidos para un agarre máximo.",
        precio:"3000",
        stock: "20",
    },
    {
        id: "4",
        titulo:"JUEGO DE COLGAR X4 -LINEA PREMIUM",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2018/05/20210630_211.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Hecho artesanalmente. Diseño original con piezas curvas y rectas. Mangos madera ergonómicos y sólido para un agarre máximo.", 
        precio:"4500",
        stock: "20",
    },
    {
        id: "5",
        titulo:"TABLA 12 C/PORTA CUCH / TENEDOR",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2020/06/P01801-3.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Tabla con funda porta cuchilla en ecocuero. Lineas con grabado láser. Canaleta para goteo. Material de alta calidad, muy fácil de limpiar y una excelente terminación.",
        precio:"3000",
        stock: "20",
    },
    {
        id: "6",
        titulo:"DISPENSER PARA JUGOS",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2021/11/1006_076-1.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Juguera de jugo con dispenser de 6 litros. Base juguera de chapa galvanizada. Vasos de jugo de 345ml. Apto para 6 personas, adaptable para mayor cantidad. Podes usarlo en el exterior, para decorar mesas al aire libre, etc. Bandeja multiuso ",
        precio:"4800",
        stock: "20",
    },
    {
        id: "7",
        titulo:"JAMONERA",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2021/11/1028_039-1.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Jamonera para pata de jamón mediana. Impermeabilizada con aceite vegetal.",
        precio:"3200",
        stock: "20",
    },
    {
        id: "8",
        titulo:"TABLA BAGUETTE 50 x 3 CUENCO CUADRADO",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2018/07/TG3579-1.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Es un complemento ideal para uso doméstico y/o profesional en la cocina. Madera ecológica, semidura y de escasa absorción, por el tratamiento que tiene es muy resistente al uso frecuente. Uso familiar o social. Moderno diseño con grabado láser. Excelente detalles terminación.",
        precio:"2900",
        stock: 20
    },
    {
        id: "9",
        titulo:"RELOJ MAPA 30 CM",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2022/05/HZ_5665.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Tamaño 30cm. Hecho de fibroplus calado.",
        precio:"2200",
        stock: "13",
    },
    {
        id: "10",
        titulo:"SET 2 ESPEJOS Y RELOJ MANDALA",
        imagen:"https://www.belloexport.com.ar/wp-content/uploads/2021/05/VB3004-08-1.jpg",
        descripcion:"DETALLES DEL PRODUCTO: Excelente detalles terminación. Uso decorativo. Posee sistema de colgado.",
        precio:"2600",
        stock: "13",
    },
]

